### ISSUE TITLE
Target Height Entity Should Track Height

### ISSUE THREAD

**Issue by barndawgie** [tjhorner/upsy-desky#38]
### Troubleshooting Guide

- [X] I have followed the steps in the troubleshooting guide and my issue is either not listed or is not solved.

### Description

If I set the Target Height via the Target Height entity, then move the desk via some other mechanism (preset, physical controller) the target height stays at whatever value it was previously set to. I'd love to see it adjust to match the actual height of the desk (which is effectively the new target, just set via some other mechanism).

### How do you manage your Upsy Desky's updates?

ESPHome YAML Config

### If you're using an ESPHome YAML config, which version of ESPHome are you running?

2023.9.3

### ESPHome Config

```YAML
---
substitutions:
  name: "upsy-desky-534044"
  friendly_name: "Upsy Desky 534044"
  device_description: "Fully Jarvis Desk Controller"

packages:
  base_config: !include config_deps/base_config.yaml
  upsy_desky:
    url: https://github.com/tjhorner/upsy-desky
    file: firmware/stock.yaml
    ref: v1.1.1

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  comment: ${device_description}
```
