### ISSUE TITLE
Fatal errors in ESPHome 2023.12.0b1

### ISSUE THREAD

**Issue by NewsGuyTor** [tjhorner/upsy-desky#41]
### Troubleshooting Guide

- [X] I have followed the steps in the troubleshooting guide and my issue is either not listed or is not solved.

### Description

With ESPHome 2023.12.0b1, Upsy Desky can't be controlled/updated with ESPHome anymore since the same pins are used twice.

### Logs

```plain text
INFO ESPHome 2023.12.0b1
INFO Reading configuration /config/esphome/upsy-desky-9fb5cc.yaml...
Failed config

output.gpio: [source <unicode string>:24]
  
  Pin 21 is used in multiple places.
  platform: gpio
  inverted: True
  id: standing_desk_up_pin
  pin: 
    number: 21
    mode: 
      output: True
      input: False
      open_drain: False
      pullup: False
      pulldown: False
    inverted: False
    ignore_strapping_warning: False
    drive_strength: 20.0
output.gpio: [source <unicode string>:29]
  
  Pin 22 is used in multiple places.
  platform: gpio
  inverted: True
  id: standing_desk_down_pin
  pin: 
    number: 22
    mode: 
      output: True
      input: False
      open_drain: False
      pullup: False
      pulldown: False
    inverted: False
    ignore_strapping_warning: False
    drive_strength: 20.0
output.gpio: [source <unicode string>:2]
  
  Pin 21 is used in multiple places.
  platform: gpio
  inverted: True
  id: button_bit1
  pin: 
    number: 21
    mode: 
      output: True
      input: False
      open_drain: False
      pullup: False
      pulldown: False
    inverted: False
    ignore_strapping_warning: False
    drive_strength: 20.0
output.gpio: [source <unicode string>:7]
  
  Pin 22 is used in multiple places.
  platform: gpio
  inverted: True
  id: button_bit2
  pin: 
    number: 22
    mode: 
      output: True
      input: False
      open_drain: False
      pullup: False
      pulldown: False
    inverted: False
    ignore_strapping_warning: False
    drive_strength: 20.0
```

### Which version of the Upsy Desky firmware config are you running?

1.2.0

### How do you manage your Upsy Desky's updates?

ESPHome YAML Config

### If you're using an ESPHome YAML config, which version of ESPHome are you running?

2023.12.0b1

### ESPHome Config

```YAML
substitutions:
  name: upsy-desky-9fb5cc
packages:
  tj_horner.upsy_desky: github://tjhorner/upsy-desky/firmware/config.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: dfsjkfdfjsdjnkfsjhkd


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
