### ISSUE TITLE
Warning in logs during compilation of omnidesk_decoder.cpp with ESPHome > 2024.6.x

### ISSUE THREAD

**Issue by 35gh** [tjhorner/upsy-desky#51]
### Troubleshooting Guide

- [X] I have followed the steps in the troubleshooting guide and my issue is either not listed or is not solved.

### Description

I get the following warning when compiling with ESPHome 2024.6.x

### Logs

```plain text
Compiling .pioenvs/upsy-desky-76dbe0/src/esphome/components/standing_desk_height/omnidesk_decoder.o
src/esphome/components/standing_desk_height/omnidesk_decoder.cpp: In member function 'virtual bool esphome::standing_desk_height::OmnideskDecoder::put(uint8_t)':
src/esphome/components/standing_desk_height/omnidesk_decoder.cpp:9:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
     if (b == 0x02 || b == 0x03 || b == 0x04) {
     ^~
src/esphome/components/standing_desk_height/omnidesk_decoder.cpp:14:3: note: here
   default:
   ^~~~~~~
```

### Which version of the Upsy Desky firmware config are you running?

4.0.0

### How do you manage your Upsy Desky's updates?

ESPHome YAML Config

### If you're using an ESPHome YAML config, which version of ESPHome are you running?

2024.6.6

### ESPHome Config

```YAML
substitutions:
  name: upsy-desky-xxxxxx
  friendly_name: Jarvis Fully 2

packages:
  tj_horner.upsy_desky: github://tjhorner/upsy-desky/firmware/base.yaml@v4.0.0

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  reboot_timeout: 0s
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO

improv_serial:

web_server:
  port: 80
  version: 2
  js_url: "https://upsy-desky.tjhorner.dev/esphome-webserver/www.js"

ota:
  password: ""
  platform: esphome

external_components:
  - source: github://tjhorner/esphome-custom-components
    components: [ project_version ]

text_sensor:
  - platform: project_version
    name: "Upsy Desky Firmware Version"
    internal: true

dashboard_import:
  package_import_url: github://tjhorner/upsy-desky/firmware/stock.yaml@v4.0.0
```
