### ISSUE TITLE
Warning in log when using web interface

### ISSUE THREAD

**Issue by 35gh** [tjhorner/upsy-desky#52]
### Troubleshooting Guide

- [X] I have followed the steps in the troubleshooting guide and my issue is either not listed or is not solved.

### Description

The following warning are printed in logs when clicking on any button of the web interface.

### Logs

```plain text
15:54:22	[W]	[web_server_idf:070][1;31m[httpd][0;33m	

Only application/x-www-form-urlencoded supported for POST request
```

### Which version of the Upsy Desky firmware config are you running?

4.0.0

### How do you manage your Upsy Desky's updates?

ESPHome YAML Config

### If you're using an ESPHome YAML config, which version of ESPHome are you running?

2024.6.6

### ESPHome Config

```YAML
substitutions:
  name: upsy-desky-xxxxxx
  friendly_name: Jarvis Fully 2

packages:
  tj_horner.upsy_desky: github://tjhorner/upsy-desky/firmware/base.yaml@v4.0.0

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  reboot_timeout: 0s
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO

improv_serial:

web_server:
  port: 80
  version: 2
  js_url: "https://upsy-desky.tjhorner.dev/esphome-webserver/www.js"

ota:
  password: ""
  platform: esphome

external_components:
  - source: github://tjhorner/esphome-custom-components
    components: [ project_version ]

text_sensor:
  - platform: project_version
    name: "Upsy Desky Firmware Version"
    internal: true

dashboard_import:
  package_import_url: github://tjhorner/upsy-desky/firmware/stock.yaml@v4.0.0
```
