### ISSUE TITLE
Packages version "unknown" in web interface

### ISSUE THREAD

**Issue by 35gh** [tjhorner/upsy-desky#53]
### Troubleshooting Guide

- [X] I have followed the steps in the troubleshooting guide and my issue is either not listed or is not solved.

### Description

Package version is "unknown" in web interface, despite custom component loaded in config.
<img width="882" alt="Capture d’écran 2024-07-03 à 16 21 54" src="https://github.com/tjhorner/upsy-desky/assets/90415090/89d9b2e7-eab3-4ecc-b29b-8692ab449f2d">

### Which version of the Upsy Desky firmware config are you running?

4.0.0

### How do you manage your Upsy Desky's updates?

ESPHome YAML Config

### If you're using an ESPHome YAML config, which version of ESPHome are you running?

2024.6.6

### ESPHome Config

```YAML
substitutions:
  name: upsy-desky-xxxxxx
  friendly_name: Jarvis Fully 2

packages:
  tj_horner.upsy_desky: github://tjhorner/upsy-desky/firmware/base.yaml@v4.0.0

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  reboot_timeout: 0s
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO

improv_serial:

web_server:
  port: 80
  version: 2
  js_url: "https://upsy-desky.tjhorner.dev/esphome-webserver/www.js"

ota:
  password: ""
  platform: esphome

external_components:
  - source: github://tjhorner/esphome-custom-components
    components: [ project_version ]

text_sensor:
  - platform: project_version
    name: "Upsy Desky Firmware Version"
    internal: true

dashboard_import:
  package_import_url: github://tjhorner/upsy-desky/firmware/stock.yaml@v4.0.0
```
