### ISSUE TITLE
Warning During Compilation: `this statement may fall through [-Wimplicit-fallthrough=]`

### ISSUE THREAD

**Issue by barndawgie** [tjhorner/upsy-desky#54]
### Troubleshooting Guide

- [X] I have followed the steps in the troubleshooting guide and my issue is either not listed or is not solved.

### Description

During compilation for wireless install, I see this warning in the logs.

### Logs

```plain text
src/esphome/components/standing_desk_height/omnidesk_decoder.cpp: In member function 'virtual bool esphome::standing_desk_height::OmnideskDecoder::put(uint8_t)':
src/esphome/components/standing_desk_height/omnidesk_decoder.cpp:9:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
     if (b == 0x02 || b == 0x03 || b == 0x04) {
     ^~
src/esphome/components/standing_desk_height/omnidesk_decoder.cpp:14:3: note: here
   default:
   ^~~~~~~
```
```


### Which version of the Upsy Desky firmware config are you running?

v4.0.0

### How do you manage your Upsy Desky's updates?

None

### If you're using an ESPHome YAML config, which version of ESPHome are you running?

2024.7.0

### ESPHome Config

```YAML
---
substitutions:
  name: "upsy-desky-534044"
  friendly_name: "Upsy Desky"
  device_description: "Fully Jarvis Desk Controller"

packages:
  upsy_desky:
    url: https://github.com/tjhorner/upsy-desky
    file: firmware/stock.yaml
    ref: v4.0.0
  base_config: !include config_deps/base_config.yaml # Contains my wi-fi and API secrets

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  comment: ${device_description}

time:
  - platform: homeassistant
    id: homeassistant_time
```
